{"uuid": "016da5f8-dc30-4248-9185-1780aaa008ec", "children": ["ff492bdb-1220-4fa9-9536-9ba18ae968e1"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "requests.exceptions.SSLError: HTTPSConnectionPool(host='passport.zhihuishu.com', port=443): Max retries exceeded with url: /user/validateAccountAndPassword (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))\n", "trace": "  File \"C:\\worksapce\\pytest\\pytestDemo-master\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\testcases\\conftest.py\", line 78, in login_fixture\n    login_info = user.login(data=payload, headers=header, cookies=cookies)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\api\\user\\user.py\", line 18, in login\n    return self.post(\"https://passport.zhihuishu.com/user/validateAccountAndPassword\", **kwargs)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\core\\rest_client.py\", line 16, in post\n    return self.request(url, \"POST\", data, json, **kwargs)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\core\\rest_client.py\", line 37, in request\n    return requests.post(url, data, json, **kwargs)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\venv\\lib\\site-packages\\requests\\api.py\", line 116, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\venv\\lib\\site-packages\\requests\\api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\venv\\lib\\site-packages\\requests\\sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\venv\\lib\\site-packages\\requests\\sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\worksapce\\pytest\\pytestDemo-master\\venv\\lib\\site-packages\\requests\\adapters.py\", line 514, in send\n    raise SSLError(e, request=request)\n"}, "start": 1623391785379, "stop": 1623391785432}], "start": 1623391785379, "stop": 1623391785726}