{"name": "test_zhs_seleniumlogintest", "status": "broken", "statusDetails": {"message": "TypeError: __init__() got an unexpected keyword argument 'chromedriver_path'", "trace": "self = <testcases.user.test_zhs_seleniumlogintest.Test_seleniumlogintest object at 0x00000277902F2E80>\n\n    def test_zhs_seleniumlogintest(self):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        chrome_options = webdriver.FirefoxOptions()\n        chrome_options.add_argument(\"--headless\")\n        chromedriver_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))),\n                                         \"config\\chromedriver.exe\")\n        logger.info(chromedriver_path)\n>       browser = webdriver.Chrome(chromedriver_path=chromedriver_path, options=chrome_options)\nE       TypeError: __init__() got an unexpected keyword argument 'chromedriver_path'\n\ntest_zhs_seleniumlogintest.py:26: TypeError"}, "attachments": [{"name": "log", "source": "fc4f6131-0ed5-422d-835a-cb7956052b92-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6eab229c-213f-4bb6-87cf-79883f5c6fee-attachment.txt", "type": "text/plain"}], "start": 1624429953676, "stop": 1624429953677, "uuid": "19cafeb5-d2d1-4b51-a729-b01b8bed0d6c", "historyId": "c06aec85e63e41e2b940ef2c08025c58", "testCaseId": "e6ed18b5be4e055550dc72885e918ffe", "fullName": "testcases.user.test_zhs_seleniumlogintest.Test_seleniumlogintest#test_zhs_seleniumlogintest", "labels": [{"name": "parentSuite", "value": "testcases.user"}, {"name": "suite", "value": "test_zhs_seleniumlogintest"}, {"name": "subSuite", "value": "Test_seleniumlogintest"}, {"name": "host", "value": "DESKTOP-FRVNKTB"}, {"name": "thread", "value": "13648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.user.test_zhs_seleniumlogintest"}]}